name: ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    if: github.repository == 'zotero-chinese/blog'
    runs-on: ubuntu-latest
    steps:
      - name: Setup JS
        uses: zotero-plugin-dev/workflows/setup-js@main

      - name: Build Docs
        run: pnpm run docs:build

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        if: github.event_name != 'pull_request'
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: zotero-chinese/website
          event-type: update-triggered-by-blog-repo
